args:
  batch_size: 96
  control_dim: 1
  control_rnn_depth: 1
  control_rnn_size: 48
  decode_every_timestep: true
  decoder_depth: 2
  decoder_mode: false
  decoder_size: 2
  discretisation_mode: TU
  encoder_depth: 2
  encoder_size: 2
  linearisation_mode: lpv
  mode_dnn: FFNet
  mode_rnn: new
  model_name: VanDerPol
  output_dim: 2
  radius: 3
  residual: false
  state_dim: 2
  use_batch_norm: false
  use_decoder: false
  x_update_mode: new
data_args:
  data_split:
  - 20
  - 20
  n_samples: 200
  n_trajectories: 200
  noise_seed: null
  noise_std: 0.0
  output_name: vdp_test_data2
  settings: data_generation/vdp.yaml
  time_horizon: 15.0
data_path: /home/giuseppe/Desktop/KTH/Thesis/flumen-G/run_data/pkl_files/vdp/vdp_test_data2.pkl
data_settings:
  control_delta: 0.2
  dynamics:
    args:
      damping: 1.0
    name: VanDerPol
  sequence_generator:
    args:
      period: 5
    name: GaussianSqWave
